
export interface AnswerData {
  answer?: number | null;
  observations: string;
  url: string;
  responsible: string;
  justification: string;
  preview: string;
  date: Date | null;
}

export const initialSectionsData = {
  "1": { sectionName: "", questions: Array.from({ length: 4 }, () => "") },
  "2": { sectionName: "", questions: Array.from({ length: 4 }, () => "") },
  "3": { sectionName: "", questions: Array.from({ length: 4 }, () => "") },
  "4": { sectionName: "", questions: Array.from({ length: 4 }, () => "") },
  "5": { sectionName: "", questions: Array.from({ length: 4 }, () => "") },
};

export const initialSectionDataQuestions: AnswerData[][] = [
  [
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
  ],
  [
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
  ],
  [
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
  ],
  [
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
  ],
  [
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
    {
      answer: null,
      observations: "",
      url: "",
      responsible: "",
      justification: "",
      preview: "",
      date: null,
    },
  ],
];